name: Build ReVanced Patches

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Clone GitLab ReVanced
        run: git clone https://gitlab.com/ReVanced/revanced-patches.git .

      - name: Build .rvp
        run: |
          chmod +x gradlew
          ./gradlew build -PgithubPackagesUsername=${{ github.actor }} -PgithubPackagesPassword=${{ secrets.GITHUB_TOKEN }}

      - name: Move the file
        run: |
          mkdir release_files
          find . -type f -name "*.rvp" -not -path "./release_files/*" -exec cp {} release_files/patches.rvp \;

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "latest"
          name: "Latest Patches"
          files: release_files/patches.rvp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
